# Generated by Django 5.2.8 on 2025-11-24 05:01

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН (ваш)')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_bic', models.CharField(max_length=9, verbose_name='БИК банка')),
                ('fns_access_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('fns_refresh_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000, null=True))),
                ('fns_integration_status', models.BooleanField(default=False)),
                ('fns_last_error', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
