# Generated by Django 5.2.8 on 2025-11-22 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Юр. адрес')),
                ('bank_details', models.JSONField(blank=True, default=dict, null=True, verbose_name='Банковские реквизиты')),
                ('last_egrul_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'inn')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('UNPAID', 'Неоплачен'), ('PAID', 'Оплачен'), ('ISSUED', 'Чек выдан'), ('CANCELLED', 'Отменен')], db_index=True, default='DRAFT', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая сумма')),
                ('services', models.JSONField(default=list, verbose_name='Позиции счета')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-number'],
                'unique_together': {('user', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fns_check_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('check_link', models.URLField(max_length=500)),
                ('check_data', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_inn', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_check', to='invoicing.invoice')),
            ],
        ),
    ]
