# Generated by Django 5.2.8 on 2025-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fns_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID счета в ФНС'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fns_invoice_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату ФНС'),
        ),
    ]
