# Generated by Django 5.2.8 on 2025-11-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_fns_invoice_id_invoice_fns_invoice_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fns_invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fns_invoice_url',
        ),
    ]
